//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Contact.ContactStrings", typeof(ContactStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Numarası.
        /// </summary>
        public static string accountnumber {
            get {
                return ResourceManager.GetString("accountnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka.
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Hesaplarımız.
        /// </summary>
        public static string bankaccounts {
            get {
                return ResourceManager.GetString("bankaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string breadcrumbmaintext {
            get {
                return ResourceManager.GetString("breadcrumbmaintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/anasayfa.
        /// </summary>
        public static string breadcrumbmainurl {
            get {
                return ResourceManager.GetString("breadcrumbmainurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string breadcrumbtext {
            get {
                return ResourceManager.GetString("breadcrumbtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÖNDER.
        /// </summary>
        public static string btngonder {
            get {
                return ResourceManager.GetString("btngonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkez.
        /// </summary>
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Seçini.
        /// </summary>
        public static string choosedepartment {
            get {
                return ResourceManager.GetString("choosedepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        public static string contactform {
            get {
                return ResourceManager.GetString("contactform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harita Koordinatları.
        /// </summary>
        public static string mapcoordinates {
            get {
                return ResourceManager.GetString("mapcoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj İçeriği.
        /// </summary>
        public static string messagecontent {
            get {
                return ResourceManager.GetString("messagecontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız şuan iletilmemektedir. Lütfen hatayı bize bildiriniz..
        /// </summary>
        public static string messagenotsent {
            get {
                return ResourceManager.GetString("messagenotsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız başarıyla iletilmiştir..
        /// </summary>
        public static string messagesent {
            get {
                return ResourceManager.GetString("messagesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muhasebe.
        /// </summary>
        public static string muhasebe {
            get {
                return ResourceManager.GetString("muhasebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız Soyadınız.
        /// </summary>
        public static string namesurname {
            get {
                return ResourceManager.GetString("namesurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız şuan iletilmemektedir. Lütfen hatayı bize bildiriniz..
        /// </summary>
        public static string notificationerror {
            get {
                return ResourceManager.GetString("notificationerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen gerekli alanları eksiksiz ve doğru bir şekilde doldurunuz..
        /// </summary>
        public static string notificationrequired {
            get {
                return ResourceManager.GetString("notificationrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız başarıyla iletilmiştir..
        /// </summary>
        public static string notificationsuccess {
            get {
                return ResourceManager.GetString("notificationsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofis.
        /// </summary>
        public static string office {
            get {
                return ResourceManager.GetString("office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pazarlama.
        /// </summary>
        public static string pazarlama {
            get {
                return ResourceManager.GetString("pazarlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * doldurulması zorunlu alanlardır..
        /// </summary>
        public static string requiredfiled {
            get {
                return ResourceManager.GetString("requiredfiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış.
        /// </summary>
        public static string satis {
            get {
                return ResourceManager.GetString("satis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu.
        /// </summary>
        public static string securitycode {
            get {
                return ResourceManager.GetString("securitycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string titlle {
            get {
                return ResourceManager.GetString("titlle", resourceCulture);
            }
        }
    }
}
