//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Home.HomeStrings", typeof(HomeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HABERLER.
        /// </summary>
        public static string bolum_haberler_baslik {
            get {
                return ResourceManager.GetString("bolum_haberler_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜM HABERLER.
        /// </summary>
        public static string bolum_haberler_tum {
            get {
                return ResourceManager.GetString("bolum_haberler_tum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/haberler.
        /// </summary>
        public static string bolum_haberler_tum_link {
            get {
                return ResourceManager.GetString("bolum_haberler_tum_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HİZMETLER.
        /// </summary>
        public static string bolum_hizmetler_baslik {
            get {
                return ResourceManager.GetString("bolum_hizmetler_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERANSLAR.
        /// </summary>
        public static string bolum_referanslar_baslik {
            get {
                return ResourceManager.GetString("bolum_referanslar_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜM REFERANSLAR.
        /// </summary>
        public static string bolum_referanslar_tum {
            get {
                return ResourceManager.GetString("bolum_referanslar_tum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/referanslar.
        /// </summary>
        public static string bolum_referanslar_tum_link {
            get {
                return ResourceManager.GetString("bolum_referanslar_tum_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLER.
        /// </summary>
        public static string bolum_urunler_baslik {
            get {
                return ResourceManager.GetString("bolum_urunler_baslik", resourceCulture);
            }
        }
    }
}
