//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Products.ProductStrings", typeof(ProductStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string breadcrumb {
            get {
                return ResourceManager.GetString("breadcrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string breadcrumblogin {
            get {
                return ResourceManager.GetString("breadcrumblogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Bilgisi İçin Tıklayınız.
        /// </summary>
        public static string fiyatbilgisi {
            get {
                return ResourceManager.GetString("fiyatbilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİYAT LİSTESİ.
        /// </summary>
        public static string fiyatlistesi {
            get {
                return ResourceManager.GetString("fiyatlistesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Listesini İndir.
        /// </summary>
        public static string fiyatlistesiniindir {
            get {
                return ResourceManager.GetString("fiyatlistesiniindir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        public static string laddress {
            get {
                return ResourceManager.GetString("laddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string lbtn {
            get {
                return ResourceManager.GetString("lbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep:.
        /// </summary>
        public static string lcep {
            get {
                return ResourceManager.GetString("lcep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket:.
        /// </summary>
        public static string lcompany {
            get {
                return ResourceManager.GetString("lcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string lfax {
            get {
                return ResourceManager.GetString("lfax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Adresi:.
        /// </summary>
        public static string lmail {
            get {
                return ResourceManager.GetString("lmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad-Soyad:.
        /// </summary>
        public static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string lnbtn {
            get {
                return ResourceManager.GetString("lnbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Adresi:.
        /// </summary>
        public static string lnmail {
            get {
                return ResourceManager.GetString("lnmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        public static string lnpass {
            get {
                return ResourceManager.GetString("lnpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre(Tekrar):.
        /// </summary>
        public static string lnrpass {
            get {
                return ResourceManager.GetString("lnrpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapın.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen gerekli alanları eksiksiz ve doğru bir şekilde doldurunuz..
        /// </summary>
        public static string loginmessageerror {
            get {
                return ResourceManager.GetString("loginmessageerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail adresi/şifre yanlış, lütfen kontrol ediniz..
        /// </summary>
        public static string loginmessagemsg {
            get {
                return ResourceManager.GetString("loginmessagemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzgünüm, Üyelik İşlemi tamamlanamadı. Lütfen yetkili ile görüşünüz..
        /// </summary>
        public static string loginmessagenew {
            get {
                return ResourceManager.GetString("loginmessagenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu mail adresi zaten kayıtlı..
        /// </summary>
        public static string loginmessagenotmail {
            get {
                return ResourceManager.GetString("loginmessagenotmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen verilerinizi kontrol ediniz, eksik veri girmeyiniz..
        /// </summary>
        public static string loginmessagenotnull {
            get {
                return ResourceManager.GetString("loginmessagenotnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen şifreler uyuşmuyor lütfen kontrol ediniz....
        /// </summary>
        public static string loginmessagepass {
            get {
                return ResourceManager.GetString("loginmessagepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yapın!.
        /// </summary>
        public static string logintitle {
            get {
                return ResourceManager.GetString("logintitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        public static string lpass {
            get {
                return ResourceManager.GetString("lpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon:.
        /// </summary>
        public static string ltel {
            get {
                return ResourceManager.GetString("ltel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyatlar.
        /// </summary>
        public static string pricestitle {
            get {
                return ResourceManager.GetString("pricestitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya da Üye Olun.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Fotoğrafları.
        /// </summary>
        public static string urunfotograflari {
            get {
                return ResourceManager.GetString("urunfotograflari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string urunler {
            get {
                return ResourceManager.GetString("urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Renkleri.
        /// </summary>
        public static string urunrenkleri {
            get {
                return ResourceManager.GetString("urunrenkleri", resourceCulture);
            }
        }
    }
}
