//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2014 AS-TON. Her hakkı saklıdır..
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri.
        /// </summary>
        public static string galeri {
            get {
                return ResourceManager.GetString("galeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/guvenlicikis.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güveli Çıkış.
        /// </summary>
        public static string logouttext {
            get {
                return ResourceManager.GetString("logouttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/arama.
        /// </summary>
        public static string m_arama_link {
            get {
                return ResourceManager.GetString("m_arama_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Listesi.
        /// </summary>
        public static string m_fiyatlistesi {
            get {
                return ResourceManager.GetString("m_fiyatlistesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string m_fiyatlistesi_link {
            get {
                return ResourceManager.GetString("m_fiyatlistesi_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri.
        /// </summary>
        public static string m_galeri {
            get {
                return ResourceManager.GetString("m_galeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/galeri.
        /// </summary>
        public static string m_galeri_link {
            get {
                return ResourceManager.GetString("m_galeri_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string m_haberler {
            get {
                return ResourceManager.GetString("m_haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/haberler.
        /// </summary>
        public static string m_haberler_link {
            get {
                return ResourceManager.GetString("m_haberler_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string m_iletisim {
            get {
                return ResourceManager.GetString("m_iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/iletisim.
        /// </summary>
        public static string m_iletisim_link {
            get {
                return ResourceManager.GetString("m_iletisim_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string m_kurumsal {
            get {
                return ResourceManager.GetString("m_kurumsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/kurumsal.
        /// </summary>
        public static string m_kurumsal_link {
            get {
                return ResourceManager.GetString("m_kurumsal_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine ve Araç Parkuru.
        /// </summary>
        public static string m_makine {
            get {
                return ResourceManager.GetString("m_makine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string m_makine_link {
            get {
                return ResourceManager.GetString("m_makine_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar.
        /// </summary>
        public static string m_referans {
            get {
                return ResourceManager.GetString("m_referans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/referanslar.
        /// </summary>
        public static string m_referans_link {
            get {
                return ResourceManager.GetString("m_referans_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler/Hizmetler.
        /// </summary>
        public static string m_urunler {
            get {
                return ResourceManager.GetString("m_urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string m_urunler_link {
            get {
                return ResourceManager.GetString("m_urunler_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/urunler.
        /// </summary>
        public static string productmenulink {
            get {
                return ResourceManager.GetString("productmenulink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/fiyatlar.
        /// </summary>
        public static string productpricesmenulink {
            get {
                return ResourceManager.GetString("productpricesmenulink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama.
        /// </summary>
        public static string txtsearch {
            get {
                return ResourceManager.GetString("txtsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Tasarım ve Yazılım &lt;a href=&quot;http://www.wortec.net&quot;&gt;WORTEC&lt;/a&gt;.
        /// </summary>
        public static string weblink {
            get {
                return ResourceManager.GetString("weblink", resourceCulture);
            }
        }
    }
}
